#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  total-dev-time
#
#  Copyright 2019 Thomas Castleman <contact@draugeros.org>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#

from os import getenv
HOME = getenv("HOME")
log = open("%s/Documents/.running-time.log" % (HOME))
totals = log.read()
log.close()
totals = totals.split("\n")
for each in range(3):
	del(totals[0])

for each in totals:
	if (each == ""):
		del(totals[totals.index(each)])

seconds_total = 0
errors = 0
for each in totals:
	minutes = 0
	seconds = 0
	each_split = each.split()
	try:
		minutes = float(each_split[0])
	except:
		minutes = 0
		errors = errors + 1
	try:
		seconds = float(each_split[1])
	except:
		seconds = 0
		errors = errors + 1
	if (minutes != 0):
		seconds_total = seconds_total + (minutes * 60)
	if (seconds != 0):
		seconds_total = seconds_total + seconds


hours_total = (seconds_total / 60) / 60
minutes_total = (hours_total - int(hours_total)) * 60
hours_total = int(hours_total)
seconds_total = (minutes_total - int(minutes_total)) * 60
minutes_total = int(minutes_total)
seconds_total = round(seconds_total)
print("\nTotal Development Time:\n")
print("%s hours %s minutes %s seconds" % (hours_total,minutes_total,seconds_total))
if (errors > 0):
	print("\n%s errors occured. Please check %s/Documents/.running-time.log for inconsistencies.\n" % (errors,HOME))
